### ISSUE TITLE
Incorrect winding

### ISSUE THREAD

**Issue by agg23** [djeedai/weldr#32]
It seems like at least some generated models have incorrect winding, which conflicts with the intended counter-clockwise winding order. This results in broken rendering in those scenarios.

![image](https://github.com/djeedai/weldr/assets/238679/8082ca14-50a6-495b-88c0-5ab19d97efb8)

See also https://github.com/warrenm/GLTFKit2/issues/59

**Comment by djeedai** [comment]
Hi @agg23, `weldr` doesn't do any rendering or even any primitive manipulation, only parsing. And I think you found already that the issue was in your Blender file anyway? Closing this, please feel free to reopen if you think this is incorrect. Thanks!

**Comment by agg23** [comment]
I don't understand. `weldr-bin` converts and places LDRAW primitives into a 3D environment in GLTF format. Thus while the winding problems probably come from the actual LDRAW models, the parser isn't properly handling it in a GLTF spec compliant manner, causing problems in many different 3D softwares.

**Comment by djeedai** [comment]
Oh sorry I was thinking about the library. Let me reopen this. It's been a while since I looked at this project 🥲

**Comment by agg23** [comment]
Thank you.

I am very naive about doing 3D stuff; I briefly looked through the GLTF generation code and didn't see anything obvious that would make fixing the winding easy. I'm guessing that after the polygons of a model are extracted, there would need to be a pass to rearrange their vertices, but again I don't really know what I'm doing.

Not having looked at it, I wonder if the `gltf` crate (which you mentioned looking at moving to) would fix the winding for us, given it's part of the spec, but I doubt it.

**Comment by djeedai** [comment]
Yes it's very possible my old and unexperienced self writing his first Rust crate did a mistake in windings. I'm not sure the `gltf` crate would help much, my guess is that the LDraw file doesn't care about winding and the `weldr-bin` conversion code just outputs triangles with a random winding which happens to work most of the time by luck maybe. I'd have to dig into the bug.

**Comment by djeedai** [comment]
@agg23 do you have a sample LDraw file exhibiting the issue?

**Comment by agg23** [comment]
A single 2x4 will show the issue: [Brick.ldr.zip](https://github.com/djeedai/weldr/files/15283069/Brick.ldr.zip)

**Comment by djeedai** [comment]
@agg23 I can't repro on `main`, I however found another bug which I think is not present in the version you're using because it was skipping some faces of the 2x4 brick. Could you please build from sources and try again? There were quite a few changes with the merging of MPD support so it's possible this is already fixed.

**Comment by agg23** [comment]
Thanks for the fix. That does improve it, but with Gestaltor I'm still seeing missing faces (the exterior walls). 
<img width="361" alt="image" src="https://github.com/djeedai/weldr/assets/238679/0c28982a-0ae4-4cbc-b7d3-69340e098bc5">

**Comment by djeedai** [comment]
@agg23 yes that's the bug I was referring to. I merged a fix a few minutes ago, did you get it?

**Comment by agg23** [comment]
Yep. Run via `cargo run`, which would automatically rebuild.

<img width="675" alt="image" src="https://github.com/djeedai/weldr/assets/238679/7094f970-8df6-4b11-80a6-41de2bdc7186">

**Comment by djeedai** [comment]
Ok I think I found another bug, since MPD landed the code recursively iterates over all sub-files of a part for the geometry, but also creates a glTF node hierarchy. This means most faces are duplicated at least twice if not more (depends on how deep the hierarchy is). This should be visible on Gestaltor if there's a hierarchy display @agg23?

**Comment by agg23** [comment]
Nothing seems obviously duplicated, but it's hard to tell. Clicking through all of the nodes doesn't appear to highlight any duplicates. 

<img width="315" alt="image" src="https://github.com/djeedai/weldr/assets/238679/e6bca3f4-7a77-4925-9c45-bff371aeab05">

However, when I went to manipulate the model to show that there doesn't appear to be a node for the long sides (the obviously missing faces in my most recent picture), I managed to produce this by manipulating the selected node:

<img width="1396" alt="image" src="https://github.com/djeedai/weldr/assets/238679/6d46ee4e-c9f7-47b7-9565-bac093f99ca1">

This is all from the same, single GLTF file. It looks like everything _but_ the outside ring of faces was duplicated, and perhaps doesn't even exist in the long exterior faces' case?

**Comment by djeedai** [comment]
> It looks like everything but the outside ring of faces was duplicated, 

Yes, the two long faces are present in the root file `3001.dat` whereas all other faces are in sub-files imported into it. So that matches.

That being said, the two long faces should be on the root node.

**Comment by agg23** [comment]
> Yes, the two long faces are present in the root file `3001.dat`

What makes those so special such that the normal is reversed? Also, the two short sides are not duplicated as well, which doesn't match what you said above.
